version: '3'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3307:3307'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && ./bin/dev"
    volumes:
      - .:/renarena2
      - rails_gem_data:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    stdin_open: true
    tty: true

volumes:
  mysql-data:
  rails_gem_data:
    driver: local